### ISSUE TITLE
queue:take with a timeout is not implemented

### ISSUE THREAD

**Issue by rybakit** [tarantool/queue#10]
The documentation [states](https://github.com/tarantool/queue#%D0%9A%D0%BE%D0%BD%D1%81%D1%8E%D0%BC%D0%B5%D1%80) that one can pass an optional timeout argument to `queue.take`, which seems not true when I look at the [sources](https://github.com/tarantool/queue/blob/master/queue/abstract/driver/utubettl.lua#L230) and [tests](https://travis-ci.org/tarantool/queue).

**Comment by bigbes** [comment]
It was a bug due to changing behavior of tonumber64. And, also, timeout argument is OK - https://github.com/tarantool/queue/blob/master/queue/abstract.lua#L36 , timeout is a feature of abstract.lua, not drivers. 
Fixed in https://github.com/tarantool/queue/commit/35d3fefe6784e4243c9624b5abaaa99fbd4790a2 . 
Thank you for your issue.

**Comment by rybakit** [comment]
Thank you for the fast response and fix!
