### ISSUE TITLE
How to avoid SPoF?

### ISSUE THREAD

**Issue by SWSAmor** [tarantool/queue#120]
Is there anyone use queue in production? If yes please help me how to do that! 
One queue instance is a single point of failure. So we need 3 or more. But with Tarantool master-master replication maybe they won't be in sync - based on what i read about. Inconsistent tubes sounds very bad to me.
I read about vshard and Avitos autovshard but even if it's good for failover than I have to fork this repo and replace all of the DMLs to the vshard.router.call. ?
I'm very uncertain about that. I appreciate any guidance.

**Comment by Totktonada** [comment]
Sorry for the long delay.

The way to go is to setup replica that will do just `box.cfg(<...>)` and fetch data. When the old master is going to be a replica, it should be restarted to stop processing tasks. When the old replica is promoted to master it should wait for all data from the past master (https://github.com/tarantool/tarantool/issues/3808) and call `require('queue')` to start processing tasks on this instance.

I know, this looks weird. I hope we should implement #60 instead.

**Comment by LeonidVas** [comment]
IMHO, this only be done with `qsync`, but in this case you will degrade the performance of the "queue".
It seems like this implementation of "queue" is not designed for this purpose.

**Comment by LeonidVas** [comment]
IMHO, this only be done with `qsync`(AFAIU this is Alexander's proposal), but in this case you will degrade the performance of the "queue". It seems like this implementation of "queue" is not designed for this purpose.

**Comment by Totktonada** [comment]
> IMHO, this only be done with `qsync`(AFAIU this is Alexander's proposal), but in this case you will degrade the performance of the "queue". It seems like this implementation of "queue" is not designed for this purpose.

Nope. And, as you correctly stated, it would lead to significant performance degradation (at least in latency).

A project, where I participate in the past, uses queues for different purposes and each microservice has a replica. In fact, we don't even have automated `wait_lsn()` and doing it manually. An instance is always started either as replica (with bare minimum of Lua code) and as a master (with full application) and becomes in this state until restart.

It was okay for us, because even with manual switchover we have enough availability to be under required SLA.

The project lands to production with tarantool-1.7.6.47 first time. There was no synchronous replication in tarantool at the moment.

**Comment by SWSAmor** [comment]
Thank you the answers.
It's a financial institution so the manual switchover isn't enough. Async also not. We mustn't lost any transaction.
We have service mesh with Consul. Two sites and every service is equal and duplicated per site except queue. Queue is the SPoF. That is what need to be solved. 
By the way the queue is working flawlessly for months so that is rather theoretic, auditing or SLA problem. But everything can fail. :-)

**Comment by Totktonada** [comment]
However, maybe, just automatic that leans on ro/rw status would be even simpler and will cover most of cases. I need to think here.

**Comment by 0x501D** [comment]
Proposal:

Create internal queue states:
[S]tartup | [R]eady | [E]nding | [W]aiting

* S:
(state changed to RW)
wait for maximum upstream lag * 2 (quiet for clients)
tasks timeout cleanup fiber starts working.
* R:
run as usual
* E:
(state changed to RO)
tasks timeout cleanup fiber stops working.
* W:
do nothing (monitor RO/RW status)

other notes:
implement per-task ttl.

**Comment by Totktonada** [comment]
The proposal sounds ok. I would like the following points to be clarified as result of working on the patch (it should be part of the documentation):

* How tasks taken in a shared session change its state, when we're going to RW, at startup? Wait until a global TTL and released then? Are there other ways aside `take()` to associate a task with a shared session? And the opposite: how tasks that are NOT associated with a shared session change its state. Released immediately at going into RW (because there is no way to release them, the old session is gone)?
* Which task states are 'immutable' for RW->RO->RW and which are not.

If you can present such information in some friendly form (some diagrams, maybe), it would be nice.

If you'll find more points around user visible behaviour (which should not be vague), let's add more questions here. If you'll define answers for given questions before the patch will be ready, let's share here as well.

**Comment by LeonidVas** [comment]
> Proposal:
> 
> Create internal queue states: [S]tartup | [R]eady | [E]nding | [W]aiting
> 
> * S:
>   (state changed to RW)
>   wait for maximum upstream lag * 2 (quiet for clients)
>   start driver (extend drivers api required).
> * R:
>   run as usual
> * E:
>   (state changed to RO)
>   stop driver.
> * W:
>   do nothing (monitor RO/RW status)
> 
> other notes: implement per-task ttl.

Hi! The proposal is ok to me.

General clarification:
As far as I understand the author of the task wanted something like synchronous spaces (not to lose a single task in the event of an instance failure), but we implementing the possibility of asynchronous replication (and switching to a replica) with the possible loss of some information when switching.

Several comments:
* Maybe [R] - Running
* I think status can be saved in the `queue.cfg`
* `ttl` - `ttr` https://github.com/tarantool/queue#set-queue-settings
* I not see the reasons to do the `ttr` per tube/task in the scope of this task (I remember that this is my proposal). It looks like we can do it later if necessary. I think this functionality if usually either used or not.
* I propose at the first stage to release all tasks before the switching.
* Does a driver will have some indicator of "useable when switching"? I mean, some customer "drivers" may not be prepared for such operations.
* The "ttl" fibers and "queue_expiration_fiber" must be stopped before the switching.

**Comment by LeonidVas** [comment]
> If you can present such information in some friendly form (some diagrams, maybe), it would be nice.

I think it is better to use `plantuml` as it is already used in the queue documentation.

**Comment by 0x501D** [comment]
```mermaid
stateDiagram-v2
direction LR
w: Waiting
note right of w
  monitor ro/rw status
end note
s: Startup
note left of s
  wait for maximum
  upstream lag * 2
  start driver
  release all tasks
end note
[*] --> r
r: Running
note right of r
  queue is ready
end note
e: Ending
note left of e
  stop driver
end note
w --> s: ro -> rw
s --> r
r --> e: rw -> ro
e --> w
```

**Comment by 0x501D** [comment]
Limitations on this solution:
1. queue will not serve tasks actions till Startup state finishes.
2. task that have been taken can be retaken from replica that became master.
